language: python
python:
  - "3.4"
  - "3.5"

services:
  - "redis"

# command to install dependencies
install:
    - python setup.py install
    - pip install coveralls

script:
    - coverage run --source=morphsvc setup.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi
branches:
  only:
    - master
    - documentation
